Build with separate build dir:
  script:
  - git submodule update --init && autoreconf -fvi && mkdir -p build && cd build &&
    ../configure && make -j4 && make check -j4 && make SKIP_LIBOPTS_CHECK=1 dist
  except:
  - tags
