Build with separate build dir:
  script:
  - git submodule update --init && autoreconf -fvi && mkdir -p build && cd build &&
    ../configure && make -j4 && make check -j4
  - cat tests/test-suite.log
  except:
  - tags
